import { lazy } from "react";

export const Home = lazy(() => import('../../../pages/home/home.jsx'))
export const Theatres = lazy(() => import('../../../pages/theatres/theatres.jsx'))
export const TheatresById = lazy(() => import('../../../pages/theatresById/theatresById.jsx'))
export const Movie = lazy(() => import('../../../pages/movie/movie.jsx'))
export const MovieById = lazy(() => import('../../../pages/movieById/movieById.jsx'))
export const Pictures = lazy(() => import('../../../pages/pictures/pictures.jsx'))
export const PictureById = lazy(() => import('../../../pages/picturesById/pictureById.jsx'))
export const Digets = lazy(() => import('../../../pages/digets/digets.jsx'))
export const DigetInfo = lazy(() => import('../../../pages/digets/digetInfo.jsx'))
export const Video = lazy(() => import('../../../pages/video/video.jsx'))
export const VideoById = lazy(() => import('../../../pages/videoById/videoById.jsx'))
export const News = lazy(() => import('../../../pages/news/news.jsx'))
export const NewsById = lazy(() => import('../../../pages/newsById/newsById.jsx'))
export const Events = lazy(() => import('../../../pages/events/events.jsx'))
export const EventsById = lazy(() => import('../../../pages/eventsById/eventsById.jsx'))